### ISSUE TITLE
Supprimer les italiques du style encadré

### ISSUE THREAD

**Issue by elpicard** [brrd/revuesorg_word_templates#18]
Une remarque d'Amandine su Books :
quand on applique le style "Encadré", tout le texte se transforme en italique. Une fois importé dans Lodel sur OEB, il reste en romain, mais du coup cela rend impossible d'intégrer des mots en italique dans l'encadré, alors que parfois il y en a dans le texte source...

Même en passant par la suite le texte en romain dans le Word, et en rajoutant les italiques, tout le texte reste en romain sur Lodel. Je trouve plus le document sur lequel j'avais réalisé ça, mais j'en ai bidouillé un mis en ligne là : https://edt-books.openedition.org/test/26468

**Comment by brrd** [comment]
Le problème n'apparaît-il que sur OEB ou également sur revues.org ?

> Même en passant par la suite le texte en romain dans le Word

Est-ce que ça veut dire que vous corrigez la définition du style pour le passer en romain ou que vous appliquez un mise en forme locale "non italique" sur le texte ?

**Comment by elpicard** [comment]
Amandine a  juste appliqué la mise en forme locale non italique, en décochant l'italique dans Word, elle n'a pas touché les propriétés du style.
