### ISSUE TITLE
Titres traduits

### ISSUE THREAD

**Issue by elpicard** [brrd/revuesorg_word_templates#2]
Ajouter au nom des styles concernés la mention (titre traduit) pour que cela soit plus parlant pour les utilisateurs.

**Comment by brrd** [comment]
Est-ce que tu pourrais m'envoyer la traduction de "titre traduit" dans les langues concernées stp ?

Je vais ajouter la mention dans les noms du menu mais pas dans les noms des styles (pour éviter d'avoir à mettre à jour les ME).

**Comment by pellenmarie** [comment]
en : Translated title
it : Titolo tradotto
es : Título traducido
pt : Título traduzido
de : Übersetzte Titel
