### ISSUE TITLE
Russe et Malgache

### ISSUE THREAD

**Issue by elpicard** [brrd/revuesorg_word_templates#3]
Ajouter les styles russes et malagaches (titres tr, résumés, mots clés) au modèle complet.

**Comment by brrd** [comment]
Pour le malgache :  
"titretraduitmg" = Lohateny voadika
"resumemg" = Famintinana
"motsclesmg" = Teny manan-danja

Pour le russe :
"titretraduitru" = заглавие
"resumeru" = Резюме
"motsclesru" = Ключевые слова

**Comment by brrd** [comment]
C'est fait depuis le commit 741406c7dae4e6a341b4d9aa8e10a89df2c70f8e.
Ce sera dispo dans la version 4.0.6.
