### ISSUE TITLE
Création du modèle italien

### ISSUE THREAD

**Issue by brrd** [brrd/revuesorg_word_templates#5]
J'ai ajouté les traductions italiennes dans un modèle en italien non publié actuellement. 

@elpicard Il faut me dire quand ce modèle est validé pour publication (ou m'envoyer les demandes de corrections si nécessaire).

Pour mémoire :

> Avec la macro de démarrage rapide, le modèle italien doit être sélectionné avec le petit "+" dans la barre de menu (utiliser le bouton "Démarrer le stylage pour Lodel" ne fonctionnera pas car ce sera la version anglaise qui sera attachée).
> 
> Il faudra aussi penser à mettre à jour le modèle éditorial sur les sites où ce modèle sera utilisé, sans quoi l'import ne passera pas.
> 
> Il n'y a pas de traductions pour les styles suivants : index thématique, période et géographie. Si vous me les envoyez je peux les ajouter.
> 
> Pour avoir aussi un modèle complet italien (en option), il faudrait traduire les styles suivants :
> 
> Styles complémentaires
> Surtitre
> Numéro du document
> Notice bibliographique
> Droits dʼauteur
> Langues
> Index de personnes
> Auteur traité
> Collaborateur
> Personnes citées
> Autres index
> Institutions
> Population
> Personnages
> Topics
> Œuvre traitée
> Ouvrages recensés
> Texte
> Accroche
> Puces

**Comment by elpicard** [comment]
pfff méga à la bourre, je reprends ça et te dis

**Comment by brrd** [comment]
@elpicard en fait c'est déjà publié depuis le 19 avril : https://github.com/OpenEdition/revuesorg_word_templates/releases/tag/4.0.6
Mais s'il y a des modifs je peux m'en occuper.
